### ISSUE TITLE
Scaffolding generates incorrect attribute

### ISSUE THREAD

**Issue by LiteracyFanatic** [efcore/EFCore.FSharp#100]
I just scaffolded an existing database and the results won't build because `[<ColumnAttribute(Type = "datetime")>]` should be `[<ColumnAttribute(TypeName = "datetime")>]`.

```
/home/jordan/src/LetsConnect/src/Server/LetsConnectDomain.fs(15,11): error FS0508: No accessible member or object constructor named 'ColumnAttribute' takes 0 arguments. The named argument 'Type' doesn't correspond to any argument or settable return property for any overload. [/home/jordan/src/LetsConnect/src/Server/Server.fsproj]
```

https://github.com/efcore/EFCore.FSharp/blob/bfac45088d362b4bf7784dd87e5af7b5e190865a/src/EFCore.FSharp/Scaffolding/FSharpEntityTypeGenerator.fs#L108

**Comment by simon-reynolds** [comment]
Hi @LiteracyFanatic, thanks for raising this!

**Comment by simon-reynolds** [comment]
Hi @LiteracyFanatic 
This should be resolved now in https://www.nuget.org/packages/EntityFrameworkCore.FSharp/5.0.3-beta004
