### ISSUE TITLE
Scaffolding doesn't set table name correctly

### ISSUE THREAD

**Issue by LiteracyFanatic** [efcore/EFCore.FSharp#101]
**Describe the bug**
I have a table in an existing database named `VendorProfile`. Scaffolding yields an entity named `VendorProfile` which is fine. But when I make a change and try to create a migration it pluralizes the name of the table to `VendorProfiles` which causes the migration to fail. I understand that removing an s from the end of a table name when creating an entity is expected behavior, but doing the reverse is a bug. This works correctly in C# because `entity.ToTable("VendorProfile");` is included in the `DbContext.OnModelCreating` method generated by scaffolding.

**Expected behavior**
Scaffolding should insert a call `ToTable` with the correct name from the database.

**Comment by simon-reynolds** [comment]
Hi @LiteracyFanatic 
This should be resolved now in https://www.nuget.org/packages/EntityFrameworkCore.FSharp/5.0.3-beta004
