### ISSUE TITLE
DbContextHelpers.fs methods return type obj instead of 'a

### ISSUE THREAD

**Issue by kirse** [efcore/EFCore.FSharp#140]
Reference back to #131 fix which updated these helpers.

On rev-ing to release 6.0.6 it appears the `DbContextHelpers.fs` helpers return type obj instead of 'a, is this intended?

Ex:

```fsharp
let myBlog = tryFindEntity<Blog> db id
// type of myBlog is now obj instead of Blog
```

I think this breaks some of the docs here as well: https://efcore.github.io/EFCore.FSharp//How_Tos/Use_DbContextHelpers.html

**Comment by simon-reynolds** [comment]
Hi @kirse 

Thanks for raising this issue, It most certainly was not intended, I've just released [6.0.7](https://www.nuget.org/packages/EntityFrameworkCore.FSharp/6.0.7) to fix that now
