### ISSUE TITLE
Sample project?

### ISSUE THREAD

**Issue by darting** [efcore/EFCore.FSharp#17]
Hi @bricelam may I know any plan to create some sample projects? 
Thanks

**Comment by bricelam** [comment]
I think don't think the implementation is finished. When it is, we'll publish a NuGet package. Once you install that package, the Scaffold-DbContext and Add-Migrations commands will just work for F# projects.

**Comment by simon-reynolds** [comment]
A sample implementation of AspNet.Identity in F# is available at https://github.com/simon-reynolds/EFCore.FSharp.MvcAuth

NuGet package published so Scaffold-DbContext and Add-Migration now works in F#
