### ISSUE TITLE
Detailed project description

### ISSUE THREAD

**Issue by xperiandri** [efcore/EFCore.FSharp#26]
What does `design time support` means in terms of EF.Core?
Could you add some explanation, please?
What can I do with this package?
Create migrations and scaffold database?

**Comment by bricelam** [comment]
> Create migrations and scaffold database?

Yep--all the design time support in EF Core a language might require. 😉

But yeah, this repo needs some love. Sometime (no idea when) I plan to sit down and publish a prerelease package to NuGet.org. I'll also clean up the README a bit and write a blog post about it.

**Comment by xperiandri** [comment]
Sounds excellent

**Comment by simon-reynolds** [comment]
In addition to our getting started guide at https://github.com/efcore/EFCore.FSharp/blob/master/GETTING_STARTED.md, we also have online documentation now available at https://efcore.github.io/EFCore.FSharp/index.html
