### ISSUE TITLE
What needs to happen for a release on NuGet.

### ISSUE THREAD

**Issue by RonaldDijks** [efcore/EFCore.FSharp#27]
What are the things that still need to happen before this could be published to NuGet, and do you need any help with that? Would love to use this in projects in the future and if you could use it I would be happy to help out :)

**Comment by bricelam** [comment]
@simontaite Is the code ready to go? (for an alpha1 release) If so, I'll schedule some time to build, sign, and publish it...

**Comment by simontaite** [comment]
@bricelam, `master` is currently good for an alpha1 release, currently targeting EF 2.2

@RonaldDijks, any help at all is appreciated. I'm particularly interested in any ideas that you may have regarding #20

**Comment by simontaite** [comment]
@bricelam, could you hold off for a couple of hours actually? Think I might have #24 almost working, will let you know soon. Would be good to be able to include automatic registration of converters for `option` types

**Comment by bricelam** [comment]
lol, hours? I wasn't even thinking about starting for at least a couple of days! 😉

**Comment by simontaite** [comment]
That gives me plenty of time then, nice one!

**Comment by sdwatkinsdev** [comment]
I'm extremely excited for this. I invested a lot of time a few months ago building an F# web app with no persistence layer, thinking "it's all just .NET under the hood, of course EF will just work when I'm ready for it". I congratulated myself for avoiding the overhead of clobbering/recreating the DB in the early stages when everything was in flux. But then I tried to add EF and everything went immediately and thoroughly pear-shaped. It such a headache trying to figure out what compromises and hacks would be required just for the minimal working prototype that the project withered.

I don't even mind having the separate C# assembly just to generate migrations, but if EFCore.FSharp can get EF to work with records with option fields, I'll weep tears of joy.

**Comment by bricelam** [comment]
See also https://github.com/aspnet/EntityFrameworkCore/issues/10731

**Comment by nikolaipaul** [comment]
So what's the current state of affairs?

**Comment by bricelam** [comment]
Sorry, swamped trying to land the EF Core 3.0 and EF 6.3 releases...

**Comment by TheSchemm** [comment]
Is this still going to happen soon?

**Comment by simontaite** [comment]
I can't give a timeframe, currently focussed on targeting .NET Core 3.1
Would hope to have a release soon though, haven't been able to give this project much attention recently but have come back on it now

**Comment by DurdSoft** [comment]
@simontaite I did a lot of the manual work upgrading from (I think) 2.1 -> 3.1 in the repo [here](https://github.com/DurdSoft/EFCore.FSharp).

I think I may have trashed some of the stuff to do with packet etc. However, the main work is located to a few files. I also extended some of the unit testing, including building the generated code. I tried to follow the "spirit" of the OO C# sources as that made/ makes updating far more simple!

I know there are definitely a few more issues with the generated code, although I haven't looked at it in a few months myself. 

Thanks.

**Comment by simontaite** [comment]
@DurdSoft 
No worries about wrecking paket. I've merged your PR and thank you for the work you've done in upgrading to 3.1 and especially around the unit testing!

Working on fixing paket now and I've got it all building almost perfectly on my own machine so will be pushing some updates either later today or tomorrow

**Comment by allistercsmith** [comment]
Any thoughts/feedback on what's left for a NuGet release? Sounds like some very positive progress being made above (and with other recent commits) 💪

**Comment by joshuapassos** [comment]
Any updates for nuget release?
