### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by metatron-the-chronicler** [efcore/EFCore.FSharp#34]
How do you use this to generate migrations in an Fsharp project? I built the code (Edited global.json to use dotnet core 3.0) but I don't see an assembly in the resultant artifacts.

**Comment by DurdSoft** [comment]
Theres a small installation guide in my PR: https://github.com/bricelam/EFCore.FSharp/pull/36. You'll need to make sure you're using EF Core 2.2.

**Comment by metatron-the-chronicler** [comment]
@DurdSoft Thank you I will take a look at your PR.

**Comment by DurdSoft** [comment]
I have also [forked](https://github.com/DurdSoft/EFCore.FSharp) the repo and added support for ef core 3.1. Hoping to put some work in to fix the update issues but no promises 🤞

**Comment by NinoFloris** [comment]
@DurdSoft very nice to hear that, do you think it's something you can push as a PR at some point?

**Comment by DurdSoft** [comment]
Once I'm happier with the quality, sure 😅

**Comment by simontaite** [comment]
Closed by #52 

Please see our new [getting started guide](https://github.com/efcore/EFCore.FSharp/blob/master/GETTING_STARTED.md)
