### ISSUE TITLE
ContextModelSnapshot missing open statement for PostgresSQL

### ISSUE THREAD

**Issue by DurdSoft** [efcore/EFCore.FSharp#35]
With PostgreSQL an open statement for `Npgsql.EntityFrameworkCore.PostgreSQL.Metadata` is required or the generated code will not build.

**Comment by simontaite** [comment]
@DurdSoft, is this no longer an issue?

**Comment by DurdSoft** [comment]
I tested it against the C# equivalent code and it produced the same result.
