### ISSUE TITLE
Migrate from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by simontaite** [efcore/EFCore.FSharp#38]
@bricelam 

The Travis CI build is linked to bricelam/EFCore.FSharp, to restore build tests for it we can create a new build pointing to efcore/EFCore.FSharp but I don't have the necessary permissions to do that

**Comment by bricelam** [comment]
Should we just use GitHub Actions instead?

**Comment by simontaite** [comment]
Sounds good to me, I'll update this issue to reflect that
