### ISSUE TITLE
Rename namespaces following project migration

### ISSUE THREAD

**Issue by simontaite** [efcore/EFCore.FSharp#39]
After migration we should change namespaces and package names from Bricelam.EntityFrameworkCore.FSharp to EFCore.FSharp

**Comment by bricelam** [comment]
Let's do EntityFrameworkCore.FSharp for the package, assembly, and root namespace. Directories, solution, and project can remain just "EFCore" for brevity.

**Comment by bricelam** [comment]
Also feel free to remove any code signing code leftover in the build. I let my certificate expire, and it was probably just overkill to begin with.

**Comment by simontaite** [comment]
Closed by #41
