### ISSUE TITLE
Can't create a migration

### ISSUE THREAD

**Issue by isaacabraham** [efcore/EFCore.FSharp#42]
Created a basic EF context (blogs and posts). Trying to create a DB from it:

1. Downloaded this repo.
1. Ran `build.cmd`
1. Referenced the generated nuget package from my application using paket.
1. Installed the ef tool locally into my app.
1. Run `dotnet ef migrations add InitialCreate`.
1. Error: The project language 'F#' isn't supported by the built-in IMigrationsCodeGenerator service. You can try looking for an additional NuGet package which supports this language; moving your DbContext type to a C# class library referenced by this project; or manually implementing and registering the design-time service for programming language.

What am I doing wrong?

**Comment by DurdSoft** [comment]
I'm not sure what's changed, but you'll need to tell EF to register the FSharp dependencies (perhaps this is automatic in ASP?), which requires a class defined somewhere in the project:

```fsharp
open EntityFrameworkCore.FSharp

type DesignTimeServices() =
        interface IDesignTimeServices with 
            member __.ConfigureDesignTimeServices(serviceCollection: IServiceCollection) = 
                let fSharpServices= EFCoreFSharpServices() :> IDesignTimeServices
                fSharpServices.ConfigureDesignTimeServices serviceCollection
                ()
```

**Comment by isaacabraham** [comment]
Cool, that worked - thank you.

I would do this but I'm not qualified to do so: please add a *basic* readme to this repository. It doesn't even say what the repository is for, let alone how to use it :-) It'll take 10 minutes to put something very simple together, and perhaps even a basic "hello world" for a migration - will save people trying this out a lot of time :-)
