### ISSUE TITLE
When scaffolding from database, string literal arrays are not generated

### ISSUE THREAD

**Issue by DurdSoft** [efcore/EFCore.FSharp#47]
**Describe the bug**
A string literal array is generated as `System.String[]` not as the actual values, e.g. `[| "A", "B" |]`. 

**To Reproduce**
Scaffold from an existing database that will require a string literal array, e.g. enumeration.

**Expected behavior**
Array values generated correctly and able to be compiled.

**Comment by simontaite** [comment]
Closed by #51
