### ISSUE TITLE
Build error: The "PackTask" task returned false but did not log an error.

### ISSUE THREAD

**Issue by reinert** [efcore/EFCore.FSharp#53]
I'm trying to build this repo in Ubuntu 20.04 but I get the following error:

```
/usr/share/dotnet/sdk/3.1.402/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error MSB4181: The "PackTask" task returned false but did not log an error.
```
Can you help me?

**Comment by baronfel** [comment]
This is an upstream issue with nuget, see [this issue](https://github.com/NuGet/Home/issues/9786) for workarounds. This should be fixed with .net 5.0 preview 2.

**Comment by reinert** [comment]
True, it's a temporary bug from nuget.

The workaround is to edit .paket\packet.restore.targets file and comment out the <ContinuePackagingAfterGeneratingNuspec>false line

Then, just make a dotnet fake build without reinstalling paket.

Thank you @baronfel for your quick help
