### ISSUE TITLE
migrationBuilder.AlterColumn miss argument construction

### ISSUE THREAD

**Issue by reinert** [efcore/EFCore.FSharp#55]
A migration was generated with the inconsistent code below:

```fsharp
migrationBuilder.AlterColumn<int>(
            name = "exchange_transaction_id"
            , table = "exchange_transactions1", nullable = false, oldType = "typedefof<int>", oldType = "Nullable(integer)", oldNullable = false)
            .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn) |> ignore
```

Notice there is two 'oldType' arguments. I searched in Microsoft docs and found this method signature. Than I found a similar argument called 'oldClrType' and changed `oldType = "typedefof<int>"` to `oldClrType = typedefof<int>` and the migration code could be executed.

I don't know why. It was pure intuition. I'm just reporting to let you know.

**Comment by simontaite** [comment]
Thanks @reinert, I'll look to get that fixed when I can

**Comment by simontaite** [comment]
Fixed in 63822f4d12f64f99c24c12913f85c9937140c934

**Comment by GunnerGuyven** [comment]
I believe this was only half-fixed.  While the field used is now correct, the value supplied is still incorrect.

- original: `oldType = "typedefof<int>"`
- current: `oldClrType = "typedefof<int>"`
- expected: `oldClrType = typedefof<int>`

This is tested at 63822f4d (current master branch).

I looked around and this seemed the most relevant ticket. I apologize if I was incorrect.

**Comment by simon-reynolds** [comment]
Hi @GunnerGuyven, you're absolutely right
Thanks for this, I'll add a fix for it later today if I get a chance

**Comment by DurdSoft** [comment]
I think I ran into this issue and fixed it as part of the [net 5.0](https://github.com/efcore/EFCore.FSharp/blob/98b99c1e164d5f82a4071c93b258749e7c590720/src/EFCore.FSharp/Migrations/Design/FSharpMigrationOperationGenerator.fs#L185) work.

**Comment by simon-reynolds** [comment]
I see that. Thanks for the fix

Happy to close this again, unless you specifically need it for EF Core 3.1.5 @GunnerGuyven?

**Comment by GunnerGuyven** [comment]
I would definitely appreciate the fix in the older version.  I found the 5.0 branch to be too unstable to use right now.  I understand either way, though, it is a minor annoyance that I can fix by hand in my current project.

**Comment by simon-reynolds** [comment]
@GunnerGuyven,
 This has been fixed in latest version on master branch

**Comment by GunnerGuyven** [comment]
I have tested on 8336dfb0 (current master) and found the fix to be again only partially complete:

` nullable = trueoldClrType = typedefof<string>,`

Notice the missing comma preceding the `oldClrType` argument.  This wasn't an issue before the latest commit.

**Comment by GunnerGuyven** [comment]
On closer look I see it actually doubled up commas on the right side of the argument, full line:
`migrationBuilder.AlterColumn<string>(
            name = "SiteID"
            , table = "Orders", maxLength = Nullable(11), nullable = trueoldClrType = typedefof<string>,
            , oldType = "Nullable(varchar(10) CHARACTER SET utf8mb4)", oldMaxLength = Nullable(10), oldNullable = true)`

**Comment by simon-reynolds** [comment]
Sorry, fixed now

**Comment by GunnerGuyven** [comment]
Confirmed, looks good now.  Thanks so much!
