### ISSUE TITLE
EF Core 5 support

### ISSUE THREAD

**Issue by tomiaijo** [efcore/EFCore.FSharp#56]
**Is your feature request related to a problem? Please describe.**
Is support for EF Core 5 planned? Seems like some of the interfaces have changed.

Output of running against EF Core 5.0.3 project:

```
→ dotnet ef migrations add Initial
Build started...
Build succeeded.
System.MissingMethodException: Method not found: 'System.String Microsoft.EntityFrameworkCore.Design.ICSharpHelper.Lambda(System.Collections.Generic.IReadOnlyList`1<System.String>)'.
   at EntityFrameworkCore.FSharp.EFCoreFSharpServices.Microsoft-EntityFrameworkCore-Design-IDesignTimeServices-ConfigureDesignTimeServices(IServiceCollection services)
   at DesignTimeServices.DesignTimeServices.Microsoft.EntityFrameworkCore.Design.IDesignTimeServices.ConfigureDesignTimeServices(IServiceCollection serviceCollection) in /home/tomiaijo/also/eol-pricing-tool/src/Server/DesignTimeServices.fs:line 13
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureDesignTimeServices(Type designTimeServicesType, IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureUserServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(DbContext context)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Method not found: 'System.String Microsoft.EntityFrameworkCore.Design.ICSharpHelper.Lambda(System.Collections.Generic.IReadOnlyList`1<System.String>)'.

```

**Comment by DurdSoft** [comment]
There's a series of API changes from 3.1.x -> 5.x that'll need to be figured out:

```csharp
// Removed
IAnnotationCodeGenerator.IsHandledByConvention
IAnnotationCodeGenerator.GenerateFluentApi
CoreAnnotationNames.TypeMapping
CoreAnnotationNames.ChangeTrackingStrategy
ChangeDetector.SkipDetectChangesAnnotation
Microsoft.EntityFrameworkCore.Internal.TypeExtensions.GetNamespaces
Microsoft.EntityFrameworkCore.Internal.IndentedStringBuilder
Type.DisplayName
Multigraph<T>
IEntityType.IsIgnoredByMigrations()
Type.GetNamespaces()

//Changed
IProperty.IsFixedLength() // bool to Nullable<bool>
ICSharpDbContextGenerator.WriteCode // changed signature
INavigation.IsCollection() // changed from method to property
```

[(also I'm getting a stackoverflow problem with paket)](https://github.com/fsprojects/Paket/issues/3907)

It shouldn't be a huge change. The code structure roughly follows the C# implementation so it should be a case of side-by-siding and figuring out how the API has changed. 

As there has never been a nuget release it would seem to make sense to shift to the latest packages. I'll have a look at it sometime this week.

**Comment by simon-reynolds** [comment]
Hi, support is planned, and slowly in progress
I've created a branch https://github.com/efcore/EFCore.FSharp/tree/net5.0 that targets the latest version of EF Core (5.0.3)

So far it's just getting everything targeting NET 5.0, I've handled the `Type.GetNamespaces()` API change but everything else is still in progress.
@DurdSoft, thanks for the list above, I'm happy to work through them with you and hopefully we can actually get a release out

**Comment by DurdSoft** [comment]
I think the 2 main pain points will be:

- Annotations - some have been removed, others deprecated. I'm not sure if there's a reason why we didn't or don't just use `IAnnotationCodeGenerator` and the DB specific implementations in EF Core? This would put `FSharpMigrationsGenerator` and `FSharpDbContextGenerator` on a diet.
- `Multigraph<T>` has been made internal. This seems to be important in making sure the snapshots are generated in a logical order. I'm not sure what the best way forward here would be.

**Comment by simon-reynolds** [comment]
Because when I first started working on this back in the 2.x days, `IAnnotationCodeGenerator` didn't exist 😄 
I'm currently working through `FSharpDbContextGenerator` at the moment and yeah, it's definitely going to be losing a lot of complexity

Trying to figure out the best way to handle `Multigraph<T>`, shall have to see what we can come up with
Maybe something that @bricelam may have some ideas on if he has a chance to take a look?

**Comment by DurdSoft** [comment]
That makes sense! I've built off your branch some more of the required code changes [here](https://github.com/DurdSoft/EFCore.FSharp/tree/durdsoft/net5.0). 2 of the unit tests are failing and I've side stepped the `Multigraph<T>` issue.

**Comment by simon-reynolds** [comment]
Perfect! Can you create a PR for that please?
Getting as far as unit tests running in order to fail means you're ahead of me 😀

**Comment by DurdSoft** [comment]
I've updated my branch to fix the tests. Most the work is don't to migrate to `AnnotationCodeGenerator`. 

There's a failing test still - the one related to snapshot enum generation that was commented out. I think there's a genuine issue here. The C# generation up to the same point looks like:


```csharp
// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations.Design;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MyNamespace
{
    [DbContext(typeof(CSharpMigrationsGeneratorTest.MyContext))]
    partial class MySnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618

            modelBuilder.Entity("Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGeneratorTest+WithAnnotations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("default_int_mapping");

                    b.Property<int>("EnumDiscriminator")
                        .HasColumnType("default_int_mapping");

                    b.HasKey("Id");

                    b.ToTable("WithAnnotations");

                    b.HasDiscriminator<int>("EnumDiscriminator")
```

Whereas the F# version:

```fsharp
namespace MyNamespace

open System
open EntityFrameworkCore.FSharp.Test.Migrations.Design
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<MyContext>)>]
type MySnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =

        modelBuilder.Entity("EntityFrameworkCore.FSharp.Test.Migrations.Design.Derived", (fun b ->

            b.HasBaseType("EntityFrameworkCore.FSharp.Test.Migrations.Design.WithAnnotations")
            b.HasDiscriminator()
```

This was probably broken in the code in 3.1 as well.

**Comment by simon-reynolds** [comment]
That's some really great work! Can you create a PR again for these changes please?

@bricelam, whenever you get a chance to see this, can you add @DurdSoft as a collaborator to this repo?

**Comment by DurdSoft** [comment]
The issue was related to the missing `Multigraph`. I've added a slightly naive implementation, which is enough to get it over the line - I'll put in a PR :thumbsup:

**Comment by DurdSoft** [comment]
I've put in another PR for a silly mistake I'd made, sorry!

There are still a few outstanding issues in scaffolding:

- Build is failing - not too sure what's changed on this ?

- `HasIndex` is failing now where it worked on 3.1. The overload resolution is always on somewhat shaky ground with the way F# plays. In this screenshot, it should be using the `Expression<_>, string` overload but doesn't seem at all happy with it. I wonder if something changed in net 5.0 (or more likely, it's something way more obvious).

<img width="707" alt="image" src="https://user-images.githubusercontent.com/24255513/108604046-67024e80-73a3-11eb-9586-03c2c5fd35ba.png">

If either argument is removed it is happy again. 

- `ToTable` is missing for modelBuilder entities on DbContext.

**Comment by simon-reynolds** [comment]
I'm working my way through the `DbContextGenerator` so I'll take care of `ToTable`

Looks like the compiler currently thinks the expression is supposed to a tuple of `obj * string` so you should be able to get `HasIndex` working if you put parentheses around the expression
`.HasIndex((fun e -> e.EntityId :> obj), "exntity_id_idx")`

**Comment by DurdSoft** [comment]
D'oh, of course. I'm going to look into migrating more of the unit tests so we can get it  1 to 1 with C#. I'm surprised none of the existing ones have caught that missing `ToTable(...)` call - and there'll probably be similar bits like that in their as well.

**Comment by simon-reynolds** [comment]
Cool, I'm going to look at tidying up the implementations in Snapshot, DbContext and Migration generators so bring them more in line with the changes in EFCore for net5.0

**Comment by simon-reynolds** [comment]
Hi @DurdSoft 
The enum test now passes, if we can add more tests to bring to parity with C# that would be great

**Comment by bricelam** [comment]
@simon-reynolds I've added @DurdSoft and made you an admin.

**Comment by tomiaijo** [comment]
I tested the net5.0 branch. Migrations seems to created ok, but have a few minor issues.

Two opens missing:
```
open Microsoft.EntityFrameworkCore.Migrations.Operations.Builders
open Microsoft.EntityFrameworkCore.Migrations.Operations
```

Some syntax errors:
- Two commas after name in `CreateTable`
- Fields have comma missing between nullable and type, and an extra comma after type
- Fields have extra comma at the end

![image](https://user-images.githubusercontent.com/700008/111871913-3529db00-8995-11eb-8bf5-ede77e8a6dc6.png)

`table.ForeignKey`, `migrationBuilder.DropTable` and `migrationBuilder.CreateIndex` have also an extra comma at the end
![image](https://user-images.githubusercontent.com/700008/111872115-57702880-8996-11eb-88b3-34b4010394e5.png)

`table.Foreignkey`is missing newline and comma after `column`:
![image](https://user-images.githubusercontent.com/700008/111873039-11679480-8997-11eb-893c-0a2b0dc7190c.png)


With these changes I was able to migrate our database, great work!

**Comment by simon-reynolds** [comment]
Hi @tomiaijo 
Thank you so much for the feedback and the kind words

I'll see what I can do about these issues and hopefully we'll then be in a good enough state to be able to release a NuGet package

**Comment by simon-reynolds** [comment]
Hi @tomiaijo,
Can you try this with the latest commits on the net5.0 branch?
I just pushed a change to correct an issue affecting CreateTable operations

I couldn't see the issues you encountered though. I was able to create an example using basic MVC authentication at https://github.com/simon-reynolds/EFCore.FSharp.MvcAuth
Can you try with the latest versions and let me know if you're still having the same problems?
I've included the latest version of the nuget package at https://github.com/simon-reynolds/EFCore.FSharp.MvcAuth/tree/main/packages
