### ISSUE TITLE
.\build.cmd fails on Windows when FSharpMigrationsGeneratorTest.fs has Unix-style line endings

### ISSUE THREAD

**Issue by AdhemarVandamme** [efcore/EFCore.FSharp#62]
When you check-out the EFCore.FSharp code through Git, Git will by default convert the Unix-style line endings (LF) from the code in the repository to Windows-style line endings (CRLF).
This behaviour can be configured globally in Git (also per repository). See [Github doc on configuring Git to handle line endings](https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings).

When you have Git configured to leave the line endings as-is — or when you have downloaded the code as a .zip-file from the GitHub website and you have unzipped the .zip-file without converting line endings, as .zip-unpacking software tends not to do —
then `.\build.cmd` fails. The .nupkg file in the dist directory is not built.

**Build log:**
```
Build Time Report
---------------------------------------------------------------------
Target                   Duration
------                   --------
Clean                    00:00:00.0293730
DotnetRestore            00:00:11.4812587
DotnetBuild              00:00:24.2832148
DotnetTest               00:00:23.6683834   (Exception of type 'Fake.DotNet.MSBuildException' was thrown.)
GenerateCoverageReport   00:00:00           (skipped)
DotnetPack               00:00:00           (skipped)
Total:                   00:00:59.5815281
Status:                  Failure
---------------------------------------------------------------------
Script reported an error:
-> BuildFailedException: Target 'DotnetTest' failed.
-> One or more errors occurred. (Exception of type 'Fake.DotNet.MSBuildException' was thrown.)
-> MSBuildException: Exception of type 'Fake.DotNet.MSBuildException' was thrown.
```

In fact, it is the tests in `FSharpMigrationsGeneratorTest.Migrations` (tests\EFCore.FSharp.Tests\Migrations\Design\FSharpMigrationsGeneratorTest.fs) that fail.

The reason is that the tests contain multi-line strings describing what content generated files should have. The generated files are generated with native line endings; and the line endings in the expected value described by the multi-line strings are those of the FSharpMigrationsGeneratorTest.fs file.

**Working workaround:**
`unix2dos tests\EFCore.FSharp.Tests\Migrations\Design\FSharpMigrationsGeneratorTest.fs` before `.\build.cmd`
Even only changing the line endings in the multi-line strings to CRLF suffices.

**Solutions:**
- Write a function that converts line endings in a string to native line endings. (I don’t know whether such a function already exists somewhere.) And call that function on all multi-line strings describing the expected value;
- **or** write a IgnoreLineEndingsDifferences string comparator. (I don’t know whether such a string comparator already exists somewhere.) And use that string comparator to compare expected and actual file content in the tests.

**Comment by simon-reynolds** [comment]
gitattributes have been updated as of https://github.com/efcore/EFCore.FSharp/commit/98b99c1e164d5f82a4071c93b258749e7c590720

Will be merged into master branch by #64
