### ISSUE TITLE
Unable to access record fields via lambdas via EntityTypeBuilder

### ISSUE THREAD

**Issue by zelenij** [efcore/EFCore.FSharp#67]
**Describe the bug**

Unable to access record fields via lambdas via EntityTypeBuilder - fails at run time during migration.

**To Reproduce**

Create a IEntityTypeConfiguration class for a record EF Core F# type.
Inside Configure(builder: EntityTypeBuilder<MyType> try to access a property via lambda:
      builder.Property(fun x -> x.FieldName)
Register this new IEntityTypeConfiguration in DbContext
Compile the projects (success)
Try to add a new migration

Observe the following exception:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: The expression 'delegateArg0 => value(Omnicv.DataModule.CoreData+userIdColumn@45).Invoke(delegateArg0)' is not a valid member access expression. The expression should represent a 
simple property or field access: 't => t.MyProperty'. (Parameter 'memberAccessExpression')                                                                                                                         
   at Microsoft.EntityFrameworkCore.Infrastructure.ExpressionExtensions.GetInternalMemberAccess[TMemberInfo](LambdaExpression memberAccessExpression)                                                              
   at Microsoft.EntityFrameworkCore.Infrastructure.ExpressionExtensions.GetMemberAccess(LambdaExpression memberAccessExpression)                                                                                   
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.Property[TProperty](Expression`1 propertyExpression)

**Expected behavior**
A new migration created successfully

**Comment by zelenij** [comment]
I did some further digging and it "seems" like converting 'a -> 'b function to Experession<Func<'a, 'b>> should be enough to achieve the goal, but doesn't seem to work.  I have the following conversion code now:

    let getNameFromBuilder (builder: EntityTypeBuilder<'a>) (extractor: 'a -> 'b) =
        let expr = <@ Func<'a, 'b>(extractor) @>
        let res = 
            QuotationToExpression expr
            |> unbox<Expression<Func<'a, 'b>>>
        builder.Property(res)

And it compiles fine, but the migration command dies with the same exception.

**Comment by simon-reynolds** [comment]
Hi @zelenij 
Is the record marked with a `[<CliMutable>]` attribute?

That will cause it to behave similarly to a C# class under the hood

**Comment by zelenij** [comment]
Yes, it is.  Here is an example (getNameFromBuilder from the previous comment):

    [<CLIMutable>]
    type CoreEventInfo =
        {
            Id: int64
            User: User
            CreatedAt: DateTime
            LastUpdated: DateTime
        }


    type CoreEventInfoConfiguration() =
        interface IEntityTypeConfiguration<CoreEventInfo> with
            member this.Configure(builder: EntityTypeBuilder<CoreEventInfo>) = 
                let userIdColumn = getNameFromBuilder builder (fun x -> x.User)
                let eventIdColumn = getNameFromBuilder builder (fun x -> x.Id)
                builder.HasIndex(userIdColumn, eventIdColumn)
                |> ignore

**Comment by simon-reynolds** [comment]
Thanks, I'll take a look and see what's going on
Is there anything particular going on in the `User` type?

**Comment by zelenij** [comment]
Not really. For the same of testing, feel free to drop it from the index and the record itself, it's not important.

**Comment by simon-reynolds** [comment]
I'm having difficulty getting the call to `builder.HasIndex` to compile

According to the [docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder.hasindex?view=efcore-5.0) `HasIndex` just takes string parameters, not lambdas

Is there anywhere you can post a minimal working reproduction?

**Comment by simon-reynolds** [comment]
The IndexExperession is of type `Expression<Func<T, object>>` so you need to cast the result to `obj`

Can you try this and let me know if it works? (I replaced User with UserId of type `int64` in your example)

```fsharp
type CoreEventInfoConfiguration() =
    interface IEntityTypeConfiguration<CoreEventInfo> with
        member this.Configure(builder: EntityTypeBuilder<CoreEventInfo>) = 
            builder.HasIndex(fun x -> (x.UserId, x.Id) :> obj) |> ignore
```
