### ISSUE TITLE
`System` namespace not included in new migrations

### ISSUE THREAD

**Issue by GunnerGuyven** [efcore/EFCore.FSharp#69]
**Describe the bug**
`open System` is not included in new migrations.  This results in uses of `Nullable`, `DateTime`, and other common types to lack definition references and compilation to fail.

**To Reproduce**
1. Create a new migration for database that has any instance of a non-required field anywhere (so that `Nullable` type will be included).
2. Attempt to apply migration to database
3. Observe failure due to uncompilable code generated in migration step

**Expected behavior**
`open System` should be included in any autogenerated file that requires the `System` namespace to compile.

**Additional context**
This bug affects version `5.0.3-alpha2`

**Comment by simon-reynolds** [comment]
5.0.3-alpha3 released
