### ISSUE TITLE
Question: any practical differences between 2 types of declarations in DbContext?

### ISSUE THREAD

**Issue by zelenij** [efcore/EFCore.FSharp#73]
Adding new types to DbContext, your intro suggests this type of syntax 

        [<DefaultValue>] val mutable countries : DbSet<Country>
        member __.Countries with get() = __.countries and set v = __.countries <- v

Wouldn't it be the same to use this syntax from practical point of view?

        member val Countries: DbSet<Country> = null with get, set

As far as migrations generation, both seem to work fine...

**Comment by simon-reynolds** [comment]
No, it does seem that this approach does result in the members remaining `null` at runtime
I'll revert these changes in the documentation

**Comment by zelenij** [comment]
Looks like this has been raised in the past: https://github.com/fsharp/fslang-suggestions/issues/103
