### ISSUE TITLE
Latest alpha generates invalid F# for migrations

### ISSUE THREAD

**Issue by zelenij** [efcore/EFCore.FSharp#74]
Looks like the timestamped file from migrations has incorrect indentations, starting from the second table, and that causes to compilation errors, naturally. 

First CreateTable is at column 9, but the second is at 13:

![image](https://user-images.githubusercontent.com/5512551/113242069-a1d09e00-92e2-11eb-8f15-fe3b050b7f93.png)

The next CreateTable is already at column 17 and so on.  I could edit the file manually, but it would be better to fix the generator :)

**Comment by simon-reynolds** [comment]
This has been corrected in https://www.nuget.org/packages/EntityFrameworkCore.FSharp/5.0.3-alpha6
