### ISSUE TITLE
Subsequent migrations have a missing unit arg to the "Up" method

### ISSUE THREAD

**Issue by Ryan-Palmer-CIT** [efcore/EFCore.FSharp#76]
Initial migrations are now working since this morning's indentation update, but a subsequent migration will omit the uint arg from its `Up` method and therefore doesn't compile unless you edit it.

![image](https://user-images.githubusercontent.com/66260121/113299361-b3bb3c80-92f4-11eb-99ca-ed1c1ddb7fd8.png)

**Comment by simon-reynolds** [comment]
Hi @Ryan-Palmer-CIT 
This should be resolved now in https://www.nuget.org/packages/EntityFrameworkCore.FSharp/5.0.3-alpha7

**Comment by Ryan-Palmer-CIT** [comment]
Again, thanks for getting it done so quickly :)
