### ISSUE TITLE
Foreign key constraints don't seem to be working

### ISSUE THREAD

**Issue by Ryan-Palmer-CIT** [efcore/EFCore.FSharp#77]
I have tried setting up a simple two way nav property between some tables.

All the tables are created and indexes are added to the foreign key columns, however no foreign key contraint is added.

I can see some stuff to do with foreign keys in the generated migration file, but it isn't getting applied to the database.

**Comment by simon-reynolds** [comment]
Hi @Ryan-Palmer-CIT 
This should be resolved now in https://www.nuget.org/packages/EntityFrameworkCore.FSharp/5.0.3-alpha7

**Comment by Ryan-Palmer-CIT** [comment]
Awesome stuff, thanks for getting it done so quickly!
