### ISSUE TITLE
Properties should be "required" by default, if not declared as option or nullable

### ISSUE THREAD

**Issue by zelenij** [efcore/EFCore.FSharp#79]
I was under impression that by default fields like string, byte[] etc would be automatically flagged as IsRequired.  However, a simple type like this:
```

    [<CLIMutable>]
    type CoreEventAttachment = 
    {
        Id: int64
        CoreEventInfoId: int64
        CoreEventInfo: CoreEventInfo
        CreatedAt: DateTime
        LastUpdatedAt: DateTime
        [<Required>]
        MimeType: string
        [<Required>]
        Attachment: byte[]
    }

```
Has Attachment and MimeType fields migration code without IsRequired - when no "Required" attribute is stamped, of course.  Interestingly, all DateTime fields are flagged as IsRequired automatically.

I looked at the code, I can see that the decision to flag is made here, but I'm not entirely sure what the logic is exactly.

https://github.com/efcore/EFCore.FSharp/blob/4834d7ae4bfe80ebd1c6c20e2d1eb10e4d461708/src/EFCore.FSharp/Migrations/Design/FSharpSnapshotGenerator.fs#L203

**Comment by simon-reynolds** [comment]
Original implementation for handling `option` types is broken
Attempting to work around it with usage of `ValueConverterSelector` but `ValueConverters` has issues at the moment around handling null values
Will keep an eye on https://github.com/dotnet/efcore/issues/13850

**Comment by zelenij** [comment]
Fun, looks like they have gone through a few iterations with this one already! :)

**Comment by zelenij** [comment]
@simon-reynolds any thoughts on the issue? Supporting option feels like rather fundamental. I see there have been no updates on the issue in the efcore project you linked - is it an absolute blocker?

**Comment by simon-reynolds** [comment]
Hi @zelenij 
At the moment ValueConverters are not called for null values in the database so it is a blocker
I'm trying to see what other ways there may be to get around this

**Comment by simon-reynolds** [comment]
@zelenij, dotnet/efcore#13850 has been closed but the functionality that allows conversion of null values will be available from EFCore 6 onwards

I'm afraid full option support will only really be feasible from then.
I'll use this ticket to track development against the EF Core 6 preview builds for handling option values
