### ISSUE TITLE
Automatically add design-time services

### ISSUE THREAD

**Issue by bricelam** [efcore/EFCore.FSharp#85]
**Is your feature request related to a problem? Please describe.**
Is there any way to avoid requiring users to manually add their own IDesignTimeServices implementation?

**Describe the solution you'd like**
The EFCore.VisualBasic project includes [an MSBuild file](https://github.com/efcore/EFCore.VisualBasic/blob/0fcff55b722e169e5da74b774a0ba9c4b0008e6f/EFCore.VisualBasic/build/netstandard2.1/EntityFrameworkCore.VisualBasic.targets) in the nupkg that adds [a source file](https://github.com/efcore/EFCore.VisualBasic/blob/0fcff55b722e169e5da74b774a0ba9c4b0008e6f/EFCore.VisualBasic/build/netstandard2.1/EFCoreVisualBasic.vb) to the project which enables `dotnet ef` to discover the design-time services automatically. Can this approach be replicated here?

**Describe alternatives you've considered**
None. This is the recommended pattern for design-time extensions.

**Additional context**
Available upon request. 😏

**Comment by simon-reynolds** [comment]
Thanks for the tip @bricelam
