### ISSUE TITLE
Example property for `DbSet` does not work

### ISSUE THREAD

**Issue by rstm-sf** [efcore/EFCore.FSharp#88]
## Description

Example property for `DbSet` does not work. This bug?

```fs
member __.Blogs : DbSet<Blog> = Unchecked.defaultof<DbSet<Blog>>
```

https://github.com/efcore/EFCore.FSharp/blob/master/GETTING_STARTED.md#update-the-model

In my option
```fs
member x.Products : DbSet<Product> = Unchecked.defaultof<DbSet<Product>>
```

![image](https://user-images.githubusercontent.com/2669927/117703514-6626cf00-b1d2-11eb-8bfa-711d44ba77f5.png)

But work with
```fs
[<DefaultValue>] val mutable products : DbSet<Product>
member x.Products with get() = x.products and set v = x.products <- v
```
![image](https://user-images.githubusercontent.com/2669927/117703828-cf0e4700-b1d2-11eb-82ad-7b4de4bd0025.png)

## Other information

* Operating System:
    - [x] windows [insert version here]
    - [ ] macOs [insert version]
    - [ ] linux [insert flavor/version here]
* Platform
    - [x] dotnet core
    - [ ] dotnet full
    - [ ] mono
* Branch or release version: 5.0.3-beta001

**Comment by simon-reynolds** [comment]
Hi @rstm-sf 

Thank you for letting me know about this, I'll have to update that documentation

If you instead define your properties like this, it should work. Turns out that reflection setters in EF don't play nice with `Unchecked.defaultof<'a>`

```fsharp
[<DefaultValue>]
val mutable private _blogs : DbSet<Blog>
member this.Blogs with get() = this._blogs and set v = this._blogs <- v
```

**Comment by rstm-sf** [comment]
Ok, thanks!
