### ISSUE TITLE
Filtering by an option column

### ISSUE THREAD

**Issue by lucasteles** [efcore/EFCore.FSharp#92]
There is any way to translate a filter by an Option property to sql ?

For instance, this query will throw an error:
```fsharp
    query {
        for p in ctx.Persons do
        where  p.Phone.IsSome
        select p.Name
    }
``` 

Workaround
One option is use the EF.Property 

```fsharp
    query {
        for p in ctx.Persons do
        where  EF.Property(p, "Phone") <> null
        select p.Name
    }
```

### UPDATE:

I managed a way to make the translation work [here](https://github.com/lucasteles/efcore-fsharp-playground/blob/master/Translators.fs)
It will even make filter by option `Value`  possible 
```fsharp
    query {
        for p in ctx.pessoas do
        where (p.Telefone.IsNone || p.Telefone.Value = "42")
        select p.Nome
    }
``` 
Do you think this should be parti of this repo?

**Comment by simon-reynolds** [comment]
Looks like some custom function may be needed to allow a direct comparison

As a workaround, this should work
```fsharp
 query {
        for p in ctx.Persons do
        where  (p.Phone <> None)
        select p.Name
    }
```

Haven't looked in any detail yet but as a first guess I would imagine that it's probably executing on the client side by bringing back the entire `Persons` DbSet first

**Comment by simon-reynolds** [comment]
Just saw your update now
Those are some excellent workarounds!  And those translations should definitely be part of this repo if you'd be willing to create a PR?

**Comment by lucasteles** [comment]
Of curse @simon-reynolds 

I will create a PR with this translations!
